# Generated by Django 3.1.7 on 2021-03-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacter', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('whatdone', models.CharField(blank=True, max_length=500)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team1', to='Diary.car')),
            ],
        ),
    ]
