# Generated by Django 3.1.7 on 2021-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to',
            name='detailscost',
            field=models.IntegerField(blank=True, default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='to',
            name='mileage',
            field=models.IntegerField(blank=True, default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='to',
            name='workcost',
            field=models.IntegerField(blank=True, default=0, max_length=500),
        ),
    ]
